#!/bin/bash
#
# Usage: bash <(curl -sk https://raw.githubusercontent.com/sjafferali/AFS_Firewall/master/afs_installer)
# Installer by: Samir J.
#
#
# MyEZinstaller for: 
# Awesome Firewall Script (AFS xD)
#

## CONFIG
AFS_REPO="https://github.com/sjafferali/AFS_Firewall.git"
bfd_path="http://s.codedby.me/bfd/bfd.tar.gz"
## CONFIG

echo
echo MyEZinstaller for:
echo "Awesome Firewall Script (AFS xD)"
echo "Repo: https://github.com/sjafferali/AFS_Firewall"
echo
echo
echo "[*] Installing git"
yum install git -y | sed "s/^/\t/"
echo -e "[*] Checking for conflicting files... "
if [[ -d /etc/firewall ]]
then
	echo /etc/firewall found...
	bak_dir="/etc/firewall_"`date +"%Y-%m-%d-%T"`
	echo -e "[*] Removing firewall... "
	mv -v /etc/firewall $bak_dir | sed "s/^/\t/"
	mv  -v /etc/init.d/firewall $bak_dir/firewall.init | sed "s/^/\t/"
	mv -v /usr/lib/systemd/system/firewall.service $bak_dir | sed "s/^/\t/"
	systemctl daemon-reload | sed "s/^/\t/"
        rm -fv /usr/sbin/firewall | sed "s/^/\t/"
        echo "[*] Backup: $bak_dir"
fi
echo -e "[*] Downloading... "
cd /root
git clone $AFS_REPO

echo -e "[*] Installing configuration files... "
mv -v /root/AFS_Firewall/firewall /etc | sed "s/^/\t/"
if [[ ! -d /etc/.firewall ]]
then
	mv -v /root/AFS_Firewall/.firewall /etc | sed "s/^/\t/"
fi
mkdir -pv /var/log/firewall | sed "s/^/\t/"

echo -e "[*] Setting up init/systemd script... " 
chmod -v u+x /etc/firewall/config/system/firewall.init | sed "s/^/\t/"
if [[ -f /bin/systemctl ]]
then
	mv -v /root/AFS_Firewall/firewall.service /usr/lib/systemd/system/firewall.service | sed "s/^/\t/"
	systemctl daemon-reload | sed "s/^/\t/"
	systemctl enable firewall | sed "s/^/\t/"
	systemctl stop firewalld | sed "s/^/\t/"
	systemctl mask firewalld | sed "s/^/\t/"
	yum install iptables-services -y | sed "s/^/\t/"
else
	ln -s /etc/firewall/config/system/firewall.init /etc/init.d/firewall | sed "s/^/\t/"
fi

echo -e "[*] Creating symlinks... "
ln -s /etc/firewall/firewall /usr/sbin/firewall | sed "s/^/\t/"
ln -s /etc/.firewall/modules/includes /etc/firewall/includes | sed "s/^/\t/"
ln -s /etc/.firewall/port-limit /etc/firewall/port-limit | sed "s/^/\t/"
ln -s /etc/.firewall/ports-in /etc/firewall/ports-in | sed "s/^/\t/"
ln -s /etc/.firewall/ports-out /etc/firewall/ports-out | sed "s/^/\t/"
ln -s /etc/.firewall/send-to-devnull /etc/firewall/send-to-devnull | sed "s/^/\t/"
ln -s /etc/.firewall/smtp-users /etc/firewall/smtp-users | sed "s/^/\t/"
ln -s /etc/.firewall/whitelist /etc/firewall/whitelist | sed "s/^/\t/"
ln -s /etc/.firewall/bruted /etc/firewall/bruted | sed "s/^/\t/"

echo -ne "[*] Removing temporary files... "
rm -fr /root/AFS_Firewall
echo Done

echo
echo Checking for control panel
if [[ -d /usr/local/cpanel ]]
then
	echo cPanel Detected. Using cPanel profile.
	/etc/firewall/firewall --profile cpanel | sed "s/^/\t/"

	if [[ ! -z `grep "# PassivePortRange          30000 50000" /etc/pure-ftpd.conf` ]]
	then
		echo FTP Passive Connections are disabled. Fixing...
		sed -i 's/# PassivePortRange          30000 50000/PassivePortRange          30000 35000/g' /etc/pure-ftpd.conf
		/etc/init.d/pure-ftpd restart | sed "s/^/\t/"
	fi
else
	echo No control panel detected. Using default profile.
	/etc/firewall/firewall --profile default | sed "s/^/\t/"
fi
echo Enabling Firewall
/etc/firewall/firewall restart | sed "s/^/\t/"
echo
echo
echo Install Completed
echo =========================
echo Binary path: /usr/sbin/firewall
echo Configration: /etc/firewall
echo
if [[ $1 == "--bfd" ]]
then
	echo "[*] --bfd passed. Installing bfd."
	if [[ -d "/usr/local/bfd" ]]
	then
		echo "[!] BFD already exists. Uninstall via /usr/local/bfd/uninstall.sh first."
		exit 1 ; 
	fi
        if [[ ! -d "/usr/local/cpanel" ]]
        then
                echo "[!] cPanel not found. This version of BFD is specifically customized for cPanel. Download official BFD package and manually install."
                exit 1 ;
        fi
	echo -ne "[*] Downloading... "
	cd /root
	wget $bfd_path &> /dev/null
	echo Done

	echo -ne "[*] Untarring... "
	tar -xzf /root/bfd.tar.gz
	echo Done

	echo "[*] Installing"
	cd bfd-*
	bash install.sh
	echo
	echo -ne "[*] Updating firewall to use cpanelbfd profile... "
	/etc/firewall/firewall --profile cpanelbfd
	echo Done
fi
